version: 2.1

orbs:
  jira: circleci/jira@1.3.1

workflows:
  test_all_PHP_and_Laravel_versions:
    jobs:
      - tests:
          context:
            - Jira
          post-steps:
            - jira/notify
          matrix:
            parameters:
              php: [php-74, php-80, php-81]
              laravel: ["5.8", "6.0", "7.0", "8.0", "9.0"]
            exclude:
              - php: [php-80, php-81, php-81, php-74]
                laravel: ["5.8", "6.0", "7.0", "9.0"]

executors:
  php-74:
    docker:
      - image: cimg/php:7.4
      - image: cimg/mysql:5.7
        environment:
          MYSQL_DATABASE: forge
    resource_class: medium+
  php-80:
    docker:
      - image: cimg/php:8.0
      - image: cimg/mysql:5.7
        environment:
          MYSQL_DATABASE: forge
    resource_class: medium+
  php-81:
    docker:
      - image: cimg/php:8.1
      - image: cimg/mysql:5.7
        environment:
          MYSQL_DATABASE: forge
    resource_class: medium+

jobs:
  tests:
    parameters:
      php:
        type: executor
      laravel:
        type: string
    executor: << parameters.php >>

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}-<< parameters.laravel >>

      - run:
          name: Install Composer dependencies
          command: |
            composer require "illuminate/contracts=^<< parameters.laravel >>" --no-update
            composer update --prefer-dist --no-interaction --no-progress

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}-<< parameters.laravel >>
          paths:
            - ./vendor

      - run:
          name: Run PHPUnit tests
          command: phpdbg -qrr  vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-html build/coverage-report --log-junit build/junit.xml
          environment:
            DB_HOST: 127.0.0.1
            DB_USERNAME: root

      - store_test_results:
          path: build

      - store_artifacts:
          path: build
